% Parametric-resolution Doppler / carrier-frequency estimator for PSK signals.
% Processing chain:
%   FIR channel filter + guarded resampling + M-th-power carrier extraction
%   + FFT peak detection + sub-bin parabolic interpolation.
%
% IMPORTANT:
%   The requested Doppler-frequency resolution is entered in the Signal
%   Parameters dialog.  It controls BOTH the physical observation time and
%   the FFT grid.  Therefore a finer requested resolution increases the
%   frame duration and reduces the number of independent time estimates.
clc;
clearvars;
close all;
fclose('all');

%% Processing parameters

% Default value displayed in the input dialog.  The user can replace it
% for every run.  Examples: 100, 10, 1, or 0.5 Hz.
defaultDopplerResolutionHz = 10;

% New sample rate after channel filtering.
% Default: Fs_new = 2 * selected signal bandwidth, capped at the original Fs.
% Increase this value (for example to 3 or 4) if more post-resampling
% frequency headroom is desired.
resampleBandwidthFactor = 2.0;

% Explicit channel-selection FIR applied BEFORE resampling.
filterOrder = 256;
filterCutoffFactor = 0.55;
filterKaiserBeta = 7.5;

% Set to 1 for the natural FFT grid.  Values 2 or 4 make the plotted FFT
% grid denser, but they do NOT improve the physical Doppler resolution.
zeroPaddingFactor = 1;

psdNFFT = 4096;
numberOfPsdSections = 200;

minimumFrameLength = 4096;

% Minimum peak-to-background ratio for accepting an estimate
minimumPeakToFloorDb = 7;

% Filter half-length used internally by MATLAB resample
resampleFilterHalfLength = 20;

% Rational approximation tolerance for Fs_new/Fs
resampleRatioTolerance = 1e-5;

%% Select IQ file

[fileName, filePath] = uigetfile( ...
    {'*.*', 'Raw IQ files (*.*)'}, ...
    'Select an IQ signal file');

if isequal(fileName, 0)
    error('No signal file was selected.');
end

fullFileName = fullfile(filePath, fileName);

%% Select IQ sample format

answerMode = questdlg( ...
    'Please select the IQ sample format.', ...
    'IQ File Format', ...
    '16-bit Integer', ...
    '32-bit Float', ...
    '16-bit Integer');

switch answerMode

    case '16-bit Integer'

        readType = 'int16=>double';
        bytesPerScalar = 2;

    case '32-bit Float'

        readType = 'single=>double';
        bytesPerScalar = 4;

    otherwise

        error('File format selection was cancelled.');
end

%% Ask signal parameters

prompt = { ...
    'Sampling frequency (Hz):', ...
    'Receiver center frequency (Hz, enter 0 for relative frequency):', ...
    'PSK modulation order: 2=BPSK, 4=QPSK/OQPSK, 8=8PSK', ...
    ['Requested Doppler-frequency resolution (Hz), ' ...
    'for example 100, 10, 1, or 0.5:']};

dialogTitle = 'Signal Parameters';

defaultInput = { ...
    '40e6', ...
    '0', ...
    '4', ...
    num2str(defaultDopplerResolutionHz, '%.12g')};

answer = inputdlg( ...
    prompt, ...
    dialogTitle, ...
    [1 75], ...
    defaultInput);

if isempty(answer)
    error('Signal parameter entry was cancelled.');
end

Fs = str2double(answer{1});
receiverCenterFrequency = str2double(answer{2});
modulationOrder = round(str2double(answer{3}));
requestedDopplerResolutionHz = str2double(answer{4});

if ~isfinite(Fs) || Fs <= 0
    error('Sampling frequency must be a positive number.');
end

if ~isfinite(receiverCenterFrequency)
    error('Receiver center frequency is invalid.');
end

if ~ismember(modulationOrder, [2 4 8])
    error('Modulation order must be 2, 4, or 8.');
end

if ~isfinite(requestedDopplerResolutionHz) || ...
        requestedDopplerResolutionHz <= 0

    error([ ...
        'Requested Doppler-frequency resolution must be ', ...
        'a positive number in Hz.']);
end

%% Open IQ file

fid = fopen(fullFileName, 'rb', 'ieee-le');

if fid < 0
    error('The selected file could not be opened.');
end

cleanupObject = onCleanup(@() fclose(fid));

fileInformation = dir(fullFileName);

totalComplexSamples = floor( ...
    fileInformation.bytes / ...
    (2 * bytesPerScalar));

if totalComplexSamples < minimumFrameLength
    error('The selected file does not contain enough IQ samples.');
end

signalDuration = totalComplexSamples / Fs;

fprintf('\nSelected file\n');
fprintf('--------------------------------------------------\n');
fprintf('%s\n', fullFileName);
fprintf('Total complex samples : %d\n', totalComplexSamples);
fprintf('Signal duration       : %.9f s\n', signalDuration);
fprintf('Original sample rate  : %.3f Hz\n', Fs);
fprintf('Requested Doppler res.: %.9f Hz\n', ...
    requestedDopplerResolutionHz);

%% Read initial samples for PSD display

numberOfPsdSamples = min( ...
    totalComplexSamples, ...
    numberOfPsdSections * psdNFFT);

psdSignal = readIQSegment( ...
    fid, ...
    0, ...
    numberOfPsdSamples, ...
    bytesPerScalar, ...
    readType);

if length(psdSignal) < minimumFrameLength
    error('Not enough samples were read for PSD calculation.');
end

psdSignal = psdSignal - mean(psdSignal);

psdSignalRms = sqrt(mean(abs(psdSignal).^2));

if psdSignalRms > eps
    psdSignal = psdSignal / psdSignalRms;
end

%% Calculate initial PSD

maximumAllowedPsdNFFT = ...
    2^floor(log2(length(psdSignal)));

usedPsdNFFT = min( ...
    psdNFFT, ...
    maximumAllowedPsdNFFT);

psdWindow = hamming(usedPsdNFFT);
psdOverlap = round(0.75 * usedPsdNFFT);

[Pxx, psdFrequency] = pwelch( ...
    psdSignal, ...
    psdWindow, ...
    psdOverlap, ...
    usedPsdNFFT, ...
    Fs, ...
    'centered');

PxxDb = 10 * log10(Pxx + eps);

%% Display PSD and select desired bandwidth

screenSize = get(0, 'ScreenSize');

figure( ...
    'Name', 'Select Signal Bandwidth', ...
    'Position', [0 0 screenSize(3) screenSize(4)]);

plot( ...
    psdFrequency / 1e6, ...
    PxxDb, ...
    'LineWidth', 1.1);

grid on;

xlabel('Frequency offset (MHz)');
ylabel('PSD (dB/Hz)');

title({ ...
    'Select the lower and upper edges of the desired signal', ...
    'The selected line is displayed immediately after each click'});

disp('Use zoom if necessary.');
disp('Press any key when you are ready to select the bandwidth.');

zoom on;
pause;
zoom off;

hold on;

%% First user click

disp('Select the first edge of the signal.');

[firstSelectedFrequencyMHz, ~] = ginput(1);

firstTemporaryLine = xline( ...
    firstSelectedFrequencyMHz, ...
    '--', ...
    sprintf('First click: %.6f MHz', ...
    firstSelectedFrequencyMHz), ...
    'LineWidth', 1.5);

drawnow;

%% Second user click

disp('Select the second edge of the signal.');

[secondSelectedFrequencyMHz, ~] = ginput(1);

secondTemporaryLine = xline( ...
    secondSelectedFrequencyMHz, ...
    '--', ...
    sprintf('Second click: %.6f MHz', ...
    secondSelectedFrequencyMHz), ...
    'LineWidth', 1.5);

drawnow;

%% Calculate selected-band parameters

selectedFrequencyMHz = sort([ ...
    firstSelectedFrequencyMHz, ...
    secondSelectedFrequencyMHz]);

lowerSelectedFrequency = ...
    selectedFrequencyMHz(1) * 1e6;

upperSelectedFrequency = ...
    selectedFrequencyMHz(2) * 1e6;

selectedBandwidth = ...
    upperSelectedFrequency - ...
    lowerSelectedFrequency;

coarseCarrierOffset = ...
    (lowerSelectedFrequency + ...
    upperSelectedFrequency) / 2;

if selectedBandwidth <= 0 || selectedBandwidth > Fs
    error('The selected bandwidth is invalid.');
end

delete(firstTemporaryLine);
delete(secondTemporaryLine);

xline( ...
    lowerSelectedFrequency / 1e6, ...
    '--', ...
    sprintf('Lower edge: %.6f MHz', ...
    lowerSelectedFrequency / 1e6), ...
    'LineWidth', 1.5);

xline( ...
    upperSelectedFrequency / 1e6, ...
    '--', ...
    sprintf('Upper edge: %.6f MHz', ...
    upperSelectedFrequency / 1e6), ...
    'LineWidth', 1.5);

xline( ...
    coarseCarrierOffset / 1e6, ...
    ':', ...
    sprintf('Coarse center: %.6f MHz', ...
    coarseCarrierOffset / 1e6), ...
    'LineWidth', 1.5);

drawnow;

fprintf('\nSelected signal\n');
fprintf('--------------------------------------------------\n');
fprintf('Lower selected edge : %.3f Hz\n', ...
    lowerSelectedFrequency);

fprintf('Upper selected edge : %.3f Hz\n', ...
    upperSelectedFrequency);

fprintf('Selected bandwidth  : %.3f Hz\n', ...
    selectedBandwidth);

fprintf('Selected band center: %.3f Hz\n', ...
    coarseCarrierOffset);

%% Design explicit channel-selection low-pass FIR

% After coarse downconversion, the selected signal nominally occupies
% approximately +/- selectedBandwidth/2.  The cutoff is placed slightly
% outside that nominal edge to avoid trimming the wanted signal.
filterCutoffFrequency = min( ...
    filterCutoffFactor * selectedBandwidth, ...
    0.48 * Fs);

normalizedCutoffFrequency = ...
    filterCutoffFrequency / (Fs / 2);

if normalizedCutoffFrequency <= 0 || ...
        normalizedCutoffFrequency >= 1

    error('The selected bandwidth is invalid for FIR filter design.');
end

filterNumerator = fir1( ...
    filterOrder, ...
    normalizedCutoffFrequency, ...
    'low', ...
    kaiser(filterOrder + 1, filterKaiserBeta));

firHalfSupportInput = ceil(filterOrder / 2);

fprintf('\nExplicit FIR channel filter\n');
fprintf('--------------------------------------------------\n');
fprintf('FIR order              : %d\n', filterOrder);
fprintf('FIR cutoff frequency   : %.6f Hz\n', ...
    filterCutoffFrequency);

%% Calculate resampling ratio

% Keep useful oversampling after channel selection.  Never upsample above
% the original sample rate because that would add computation but no new
% information.
targetResampledFs = min( ...
    Fs, ...
    resampleBandwidthFactor * selectedBandwidth);

% Safety check: the explicit FIR passband must fit comfortably below the
% Nyquist limit of the new sampling rate.
minimumSafeResampledFs = ...
    2.10 * filterCutoffFrequency;

if targetResampledFs < minimumSafeResampledFs

    targetResampledFs = min( ...
        Fs, ...
        minimumSafeResampledFs);
end

if abs(targetResampledFs - Fs) <= ...
        resampleRatioTolerance * Fs

    p = 1;
    q = 1;

else

    [p, q] = rat( ...
        targetResampledFs / Fs, ...
        resampleRatioTolerance);

    % Avoid excessively large rational conversion factors
    if max(p, q) > 5000

        warning([ ...
            'The initial rational resampling ratio was too large. ', ...
            'A less strict approximation will be used.']);

        [p, q] = rat( ...
            targetResampledFs / Fs, ...
            1e-4);
    end
end

resampledFs = Fs * p / q;

fprintf('\nResampling parameters\n');
fprintf('--------------------------------------------------\n');
fprintf('Target sample rate     : %.6f Hz\n', ...
    targetResampledFs);

fprintf('Actual sample rate     : %.6f Hz\n', ...
    resampledFs);

fprintf('Interpolation factor p : %d\n', p);
fprintf('Decimation factor q    : %d\n', q);

fprintf('Sample-rate error      : %.6f Hz\n', ...
    resampledFs - targetResampledFs);

%% Determine input and output frame lengths

% For an M-th-power estimator, one FFT bin in the powered spectrum becomes
% 1/M of a bin after mapping the result back to the original carrier.  The
% natural (non-zero-padded) carrier/Doppler resolution is therefore
%
%       Delta_f_D = Fs_resampled / (M * N_frame).
%
% Choose N_frame from the user-requested resolution.  It is also forced to
% be at least minimumFrameLength and to have the form p*K, so the matching
% original-rate frame has exactly q*K samples.
requiredResampledFrameLength = ceil( ...
    resampledFs / ...
    (modulationOrder * requestedDopplerResolutionHz));

requiredResampledFrameLength = max( ...
    minimumFrameLength, ...
    requiredResampledFrameLength);

K = max( ...
    1, ...
    ceil(requiredResampledFrameLength / p));

inputFrameLength = q * K;
resampledFrameLength = p * K;

observationTime = ...
    inputFrameLength / Fs;

achievedDopplerResolutionHz = ...
    resampledFs / ...
    (modulationOrder * resampledFrameLength);

minimumFullFileResolutionHz = ...
    1 / (modulationOrder * signalDuration);

if inputFrameLength > totalComplexSamples

    error([ ...
        'The IQ recording is too short for the requested Doppler ', ...
        'resolution. Requested = %.9f Hz, approximate best possible ', ...
        'with this complete file = %.9f Hz. Increase the requested ', ...
        'resolution value or use a longer recording.'], ...
        requestedDopplerResolutionHz, ...
        minimumFullFileResolutionHz);
end

fprintf('\nFrame parameters\n');
fprintf('--------------------------------------------------\n');
fprintf('Requested Doppler resolution : %.9f Hz\n', ...
    requestedDopplerResolutionHz);

fprintf('Achieved Fourier resolution  : %.9f Hz\n', ...
    achievedDopplerResolutionHz);

fprintf('Input samples per frame     : %d\n', ...
    inputFrameLength);

fprintf('Resampled samples per frame : %d\n', ...
    resampledFrameLength);

fprintf('Observation time per frame  : %.9f s\n', ...
    observationTime);

fprintf('Nominal time resolution      : %.9f s\n', ...
    observationTime);

%% Determine guard required by BOTH FIR filtering and resampling

% MATLAB resample uses an internal anti-aliasing FIR filter.  In addition,
% this hybrid version applies an explicit FIR before resampling.  Therefore
% each frame is read with guard samples on both sides, filtered as an
% extended block, resampled, and only the central core is analyzed.
approximateResampleSupportInput = ceil( ...
    resampleFilterHalfLength * ...
    max(p, q) / p);

guardInputLength = ...
    firHalfSupportInput + ...
    2 * approximateResampleSupportInput;

% Make the guard interval a multiple of q so that its resampled
% length maps to an integer number of output samples.
guardInputLength = ...
    ceil(guardInputLength / q) * q;

fprintf('Input guard length         : %d samples\n', ...
    guardInputLength);

%% Carrier FFT parameters after resampling

if ~isfinite(zeroPaddingFactor) || zeroPaddingFactor < 1
    error('zeroPaddingFactor must be greater than or equal to 1.');
end

carrierNFFT = 2^nextpow2( ...
    zeroPaddingFactor * ...
    resampledFrameLength);

fftBinSpacing = ...
    resampledFs / carrierNFFT;

carrierGridSpacing = ...
    fftBinSpacing / modulationOrder;

fourierCarrierScale = ...
    achievedDopplerResolutionHz;

fprintf('\nCarrier FFT parameters\n');
fprintf('--------------------------------------------------\n');
fprintf('Carrier FFT length          : %d\n', ...
    carrierNFFT);

fprintf('Requested Doppler resolution: %.9f Hz\n', ...
    requestedDopplerResolutionHz);

fprintf('Achieved Fourier resolution : %.9f Hz\n', ...
    achievedDopplerResolutionHz);

fprintf('FFT-bin spacing             : %.6f Hz\n', ...
    fftBinSpacing);

fprintf('Displayed Doppler-grid step : %.9f Hz\n', ...
    carrierGridSpacing);

fprintf('Physical Fourier scale      : %.9f Hz\n', ...
    fourierCarrierScale);

fprintf('Zero-padding factor         : %.3f\n', ...
    zeroPaddingFactor);

%% Prepare full-file processing

% Every processed frame must contain the complete observation interval;
% otherwise the final partial frame would have a worse physical resolution.
% Regular frames do not overlap.  If samples remain at the end, one final
% full-length frame is shifted to the file end and may overlap the preceding
% frame.  This retains the requested resolution while covering the tail.
lastPossibleFrameStart = ...
    totalComplexSamples - inputFrameLength;

frameStartSamples = ...
    (0:inputFrameLength:lastPossibleFrameStart).';

if isempty(frameStartSamples) || ...
        frameStartSamples(end) ~= lastPossibleFrameStart

    frameStartSamples(end + 1, 1) = ...
        lastPossibleFrameStart;
end

numberOfFrames = length(frameStartSamples);

timeVector = nan(numberOfFrames, 1);

rawResidualFrequency = nan(numberOfFrames, 1);
interpolatedResidualFrequency = nan(numberOfFrames, 1);

rawCarrierFrequency = nan(numberOfFrames, 1);
interpolatedCarrierFrequency = nan(numberOfFrames, 1);

peakToFloorDb = nan(numberOfFrames, 1);
fractionalBinOffsetVector = nan(numberOfFrames, 1);

previousInterpolatedResidual = NaN;

resampledSpectrumExampleShown = false;
carrierPeakExampleShown = false;

fprintf('\nProcessing the complete file...\n');
fprintf('Number of full-resolution frames: %d\n', ...
    numberOfFrames);

%% Process the complete file

for frameIndex = 1:numberOfFrames

    %% Determine original-rate frame position

    coreStartSample = ...
        frameStartSamples(frameIndex);

    coreSampleCount = inputFrameLength;
    expectedOutputCount = resampledFrameLength;

    %% Add left and right guard intervals

    readStartSample = max( ...
        0, ...
        coreStartSample - guardInputLength);

    readStopSample = min( ...
        totalComplexSamples, ...
        coreStartSample + ...
        coreSampleCount + ...
        guardInputLength);

    readSampleCount = ...
        readStopSample - readStartSample;

    inputExtendedSignal = readIQSegment( ...
        fid, ...
        readStartSample, ...
        readSampleCount, ...
        bytesPerScalar, ...
        readType);

    if isempty(inputExtendedSignal)
        break;
    end

    %% Transfer the selected band to zero frequency

    absoluteSampleIndices = ...
        readStartSample + ...
        (0:length(inputExtendedSignal)-1).';

    downconversionOscillator = exp( ...
        -1i * 2 * pi * ...
        coarseCarrierOffset * ...
        absoluteSampleIndices / Fs);

    zeroCenteredExtendedSignal = ...
        inputExtendedSignal .* ...
        downconversionOscillator;

    %% Explicit FIR channel filtering on the guarded block

    % The symmetric FIR is applied to the complete extended block.  Using
    % conv(...,'same') keeps the filtered samples aligned with the original
    % sample indices.  The guard interval keeps convolution edge effects
    % away from the central section used for carrier estimation.
    filteredExtendedSignal = conv( ...
        zeroCenteredExtendedSignal, ...
        filterNumerator, ...
        'same');

    %% Resample the already channel-filtered signal

    % resample adds its own anti-aliasing FIR.  The explicit FIR above is
    % still useful because it rejects adjacent channels/interferers before
    % decimation.
    if p == 1 && q == 1

        resampledExtendedSignal = ...
            filteredExtendedSignal;

    else

        resampledExtendedSignal = resample( ...
            filteredExtendedSignal, ...
            p, ...
            q, ...
            resampleFilterHalfLength);
    end

    %% Extract only the central, transient-free output section

    leftInputSampleCount = ...
        coreStartSample - readStartSample;

    leftOutputSampleCount = round( ...
        leftInputSampleCount * p / q);

    centralOutputStart = ...
        leftOutputSampleCount + 1;

    centralOutputStop = min( ...
        length(resampledExtendedSignal), ...
        centralOutputStart + ...
        expectedOutputCount - 1);

    if centralOutputStart > ...
            length(resampledExtendedSignal)

        continue;
    end

    resampledSignal = ...
        resampledExtendedSignal( ...
        centralOutputStart:centralOutputStop);

    if length(resampledSignal) < resampledFrameLength
        continue;
    end

    % Keep an identical number of samples in every carrier FFT so that all
    % estimates have exactly the same physical Doppler resolution.
    resampledSignal = ...
        resampledSignal(1:resampledFrameLength);

    %% Remove DC and normalize RMS power

    resampledSignal = ...
        resampledSignal - mean(resampledSignal);

    signalRms = sqrt( ...
        mean(abs(resampledSignal).^2));

    if ~isfinite(signalRms) || signalRms <= eps
        continue;
    end

    resampledSignal = ...
        resampledSignal / signalRms;

    %% Display one spectrum after downconversion and resampling

    if ~resampledSpectrumExampleShown

        exampleNFFT = min( ...
            8192, ...
            2^floor(log2(length(resampledSignal))));

        exampleWindow = hamming(exampleNFFT);
        exampleOverlap = round(0.75 * exampleNFFT);

        [resampledPsd, resampledPsdFrequency] = pwelch( ...
            resampledSignal, ...
            exampleWindow, ...
            exampleOverlap, ...
            exampleNFFT, ...
            resampledFs, ...
            'centered');

        resampledPsdDb = ...
            10 * log10(resampledPsd + eps);

        figure( ...
            'Name', ...
            'Spectrum After FIR Filtering and Resampling');

        plot( ...
            resampledPsdFrequency, ...
            resampledPsdDb, ...
            'LineWidth', 1.2);

        hold on;

        xline( ...
            0, ...
            '--', ...
            'Zero frequency');

        xline( ...
            -resampledFs / 2, ...
            ':', ...
            'New lower Nyquist limit');

        xline( ...
            resampledFs / 2, ...
            ':', ...
            'New upper Nyquist limit');

        xline( ...
            -filterCutoffFrequency, ...
            '--', ...
            'FIR lower cutoff');

        xline( ...
            filterCutoffFrequency, ...
            '--', ...
            'FIR upper cutoff');

        grid on;

        xlabel('Frequency offset (Hz)');
        ylabel('PSD (dB/Hz)');

        title({ ...
            'Selected Signal After Downconversion, FIR Filtering, and Resampling', ...
            sprintf('New sample rate = %.3f Hz', ...
            resampledFs)});

        resampledSpectrumExampleShown = true;

        drawnow;
    end

    %% M-th power carrier extraction

    poweredSignal = ...
        resampledSignal .^ modulationOrder;

    carrierWindow = hann( ...
        length(poweredSignal), ...
        'periodic');

    poweredSpectrum = fftshift( ...
        fft( ...
        poweredSignal .* carrierWindow, ...
        carrierNFFT));

    poweredSpectrumPower = ...
        abs(poweredSpectrum).^2;

    poweredFrequencyAxis = ...
        (-carrierNFFT/2:carrierNFFT/2-1).' * ...
        resampledFs / carrierNFFT;

    %% Detect strongest FFT bin

    [maximumPeakPower, maximumPeakIndex] = ...
        max(poweredSpectrumPower);

    %% Calculate peak-to-background ratio

    backgroundMask = true(carrierNFFT, 1);

    peakGuardLength = 8;

    guardStart = max( ...
        1, ...
        maximumPeakIndex - peakGuardLength);

    guardStop = min( ...
        carrierNFFT, ...
        maximumPeakIndex + peakGuardLength);

    backgroundMask(guardStart:guardStop) = false;

    backgroundPower = median( ...
        poweredSpectrumPower(backgroundMask));

    currentPeakToFloorDb = 10 * log10( ...
        maximumPeakPower / ...
        (backgroundPower + eps));

    peakToFloorDb(frameIndex) = ...
        currentPeakToFloorDb;

    %% Raw FFT-bin estimate

    rawPeakBinPosition = ...
        (maximumPeakIndex - 1) - ...
        carrierNFFT / 2;

    rawPoweredPeakFrequency = ...
        rawPeakBinPosition * ...
        resampledFs / carrierNFFT;

    %% Sub-bin parabolic interpolation

    fractionalBinOffset = 0;

    if maximumPeakIndex > 1 && ...
            maximumPeakIndex < carrierNFFT

        leftValue = log( ...
            poweredSpectrumPower( ...
            maximumPeakIndex - 1) + eps);

        centerValue = log( ...
            poweredSpectrumPower( ...
            maximumPeakIndex) + eps);

        rightValue = log( ...
            poweredSpectrumPower( ...
            maximumPeakIndex + 1) + eps);

        interpolationDenominator = ...
            leftValue - ...
            2 * centerValue + ...
            rightValue;

        if abs(interpolationDenominator) > eps

            fractionalBinOffset = ...
                0.5 * ...
                (leftValue - rightValue) / ...
                interpolationDenominator;

            fractionalBinOffset = max( ...
                -0.5, ...
                min(0.5, fractionalBinOffset));
        end
    end

    fractionalBinOffsetVector(frameIndex) = ...
        fractionalBinOffset;

    interpolatedPeakBinPosition = ...
        rawPeakBinPosition + ...
        fractionalBinOffset;

    interpolatedPoweredPeakFrequency = ...
        interpolatedPeakBinPosition * ...
        resampledFs / carrierNFFT;

    %% Resolve M-th-power frequency ambiguity

    ambiguityIndices = ...
        (-modulationOrder:modulationOrder).';

    rawResidualCandidates = ...
        (rawPoweredPeakFrequency + ...
        ambiguityIndices * resampledFs) / ...
        modulationOrder;

    interpolatedResidualCandidates = ...
        (interpolatedPoweredPeakFrequency + ...
        ambiguityIndices * resampledFs) / ...
        modulationOrder;

    maximumExpectedResidual = min( ...
        0.60 * selectedBandwidth, ...
        0.49 * resampledFs);

    validCandidateMask = ...
        abs(interpolatedResidualCandidates) <= ...
        maximumExpectedResidual;

    candidateIndices = find(validCandidateMask);

    if isempty(candidateIndices)

        candidateIndices = ...
            (1:length(ambiguityIndices)).';
    end

    candidateInterpolatedValues = ...
        interpolatedResidualCandidates( ...
        candidateIndices);

    if isfinite(previousInterpolatedResidual)

        [~, localCandidateIndex] = min( ...
            abs( ...
            candidateInterpolatedValues - ...
            previousInterpolatedResidual));

    else

        [~, localCandidateIndex] = min( ...
            abs(candidateInterpolatedValues));
    end

    selectedCandidateIndex = ...
        candidateIndices(localCandidateIndex);

    currentRawResidual = ...
        rawResidualCandidates( ...
        selectedCandidateIndex);

    currentInterpolatedResidual = ...
        interpolatedResidualCandidates( ...
        selectedCandidateIndex);

    selectedAmbiguityIndex = ...
        ambiguityIndices( ...
        selectedCandidateIndex);

    %% Accept current frame

    if currentPeakToFloorDb >= minimumPeakToFloorDb

        rawResidualFrequency(frameIndex) = ...
            currentRawResidual;

        interpolatedResidualFrequency(frameIndex) = ...
            currentInterpolatedResidual;

        rawCarrierFrequency(frameIndex) = ...
            receiverCenterFrequency + ...
            coarseCarrierOffset + ...
            currentRawResidual;

        interpolatedCarrierFrequency(frameIndex) = ...
            receiverCenterFrequency + ...
            coarseCarrierOffset + ...
            currentInterpolatedResidual;

        previousInterpolatedResidual = ...
            currentInterpolatedResidual;

        %% Display one example of raw and interpolated peak

        if ~carrierPeakExampleShown

            poweredSpectrumDb = ...
                10 * log10( ...
                poweredSpectrumPower + eps);

            backgroundPowerDb = ...
                10 * log10( ...
                backgroundPower + eps);

            validityThresholdDb = ...
                backgroundPowerDb + ...
                minimumPeakToFloorDb;

            equivalentCarrierFrequencyAxis = ...
                (poweredFrequencyAxis + ...
                selectedAmbiguityIndex * ...
                resampledFs) / ...
                modulationOrder;

            displayHalfSpan = max( ...
                200 * carrierGridSpacing, ...
                0.02 * resampledFs / ...
                modulationOrder);

            displayMask = ...
                equivalentCarrierFrequencyAxis >= ...
                currentInterpolatedResidual - ...
                displayHalfSpan & ...
                equivalentCarrierFrequencyAxis <= ...
                currentInterpolatedResidual + ...
                displayHalfSpan;

            peakPowerDb = ...
                10 * log10( ...
                maximumPeakPower + eps);

            figure( ...
                'Name', ...
                'Raw and Interpolated Carrier Peak');

            plot( ...
                equivalentCarrierFrequencyAxis(displayMask), ...
                poweredSpectrumDb(displayMask), ...
                'LineWidth', 1.2);

            hold on;

            plot( ...
                currentRawResidual, ...
                peakPowerDb, ...
                'o', ...
                'MarkerSize', 8, ...
                'LineWidth', 1.5);

            plot( ...
                currentInterpolatedResidual, ...
                peakPowerDb, ...
                'x', ...
                'MarkerSize', 9, ...
                'LineWidth', 1.8);

            xline( ...
                currentRawResidual, ...
                '--', ...
                sprintf( ...
                'Raw bin: %.3f Hz', ...
                currentRawResidual));

            xline( ...
                currentInterpolatedResidual, ...
                ':', ...
                sprintf( ...
                'Interpolated: %.3f Hz', ...
                currentInterpolatedResidual));

            yline( ...
                backgroundPowerDb, ...
                ':', ...
                'Background level');

            yline( ...
                validityThresholdDb, ...
                '--', ...
                'Validity threshold');

            grid on;

            xlabel( ...
                'Equivalent residual carrier frequency (Hz)');

            ylabel('Power spectrum (dB)');

            title({ ...
                sprintf( ...
                'Power-%d Carrier Extraction Peak', ...
                modulationOrder), ...
                sprintf( ...
                ['Raw = %.3f Hz, Interpolated = %.3f Hz, ' ...
                'Difference = %.3f Hz'], ...
                currentRawResidual, ...
                currentInterpolatedResidual, ...
                currentInterpolatedResidual - ...
                currentRawResidual), ...
                sprintf( ...
                'Peak-to-background ratio = %.2f dB', ...
                currentPeakToFloorDb)});

            legend( ...
                'Power spectrum', ...
                'Raw FFT-bin estimate', ...
                'Sub-bin interpolated estimate', ...
                'Location', ...
                'best');

            carrierPeakExampleShown = true;

            drawnow;
        end
    end

    %% Save frame-center time

    timeVector(frameIndex) = ...
        (coreStartSample + ...
        (coreSampleCount - 1) / 2) / Fs;

    if mod(frameIndex, 100) == 0 || ...
            frameIndex == numberOfFrames

        fprintf( ...
            'Processed frame %d of %d\n', ...
            frameIndex, ...
            numberOfFrames);
    end
end

%% Remove unused entries

processedFrames = find( ...
    isfinite(timeVector), ...
    1, ...
    'last');

if isempty(processedFrames)
    error('No frame was successfully processed.');
end

timeVector = ...
    timeVector(1:processedFrames);

rawResidualFrequency = ...
    rawResidualFrequency(1:processedFrames);

interpolatedResidualFrequency = ...
    interpolatedResidualFrequency(1:processedFrames);

rawCarrierFrequency = ...
    rawCarrierFrequency(1:processedFrames);

interpolatedCarrierFrequency = ...
    interpolatedCarrierFrequency(1:processedFrames);

peakToFloorDb = ...
    peakToFloorDb(1:processedFrames);

fractionalBinOffsetVector = ...
    fractionalBinOffsetVector(1:processedFrames);

%% Select valid estimates

validEstimateMask = ...
    isfinite(rawCarrierFrequency) & ...
    isfinite(interpolatedCarrierFrequency);

if ~any(validEstimateMask)

    error([ ...
        'No valid carrier estimate was found. ', ...
        'Verify the selected bandwidth, modulation order, ', ...
        'and minimumPeakToFloorDb.']);
end

validTime = ...
    timeVector(validEstimateMask);

validRawCarrier = ...
    rawCarrierFrequency(validEstimateMask);

validInterpolatedCarrier = ...
    interpolatedCarrierFrequency(validEstimateMask);

validRawResidual = ...
    rawResidualFrequency(validEstimateMask);

validInterpolatedResidual = ...
    interpolatedResidualFrequency(validEstimateMask);

%% Plot raw and interpolated carrier estimates

figure( ...
    'Name', ...
    'Raw and Interpolated Carrier Frequency');

plot( ...
    validTime, ...
    validRawCarrier, ...
    'o-', ...
    'MarkerSize', 3, ...
    'LineWidth', 0.8);

hold on;

plot( ...
    validTime, ...
    validInterpolatedCarrier, ...
    '.-', ...
    'MarkerSize', 8, ...
    'LineWidth', 1.1);

grid on;

xlabel('Time (s)');

if receiverCenterFrequency == 0

    ylabel('Carrier frequency offset (Hz)');

    title({ ...
        'Raw and Interpolated Carrier Estimates', ...
        'Frequency is relative to the IQ recording center'});

else

    ylabel('Carrier frequency (Hz)');

    title( ...
        'Raw and Interpolated Carrier Estimates');
end

legend( ...
    sprintf( ...
    'Raw FFT-bin estimate, grid = %.3f Hz', ...
    carrierGridSpacing), ...
    'Sub-bin parabolic estimate', ...
    'Location', ...
    'best');

%% Plot both estimates around a common reference

referenceCarrierFrequency = median( ...
    validInterpolatedCarrier);

rawCarrierVariation = ...
    validRawCarrier - ...
    referenceCarrierFrequency;

interpolatedCarrierVariation = ...
    validInterpolatedCarrier - ...
    referenceCarrierFrequency;

figure( ...
    'Name', ...
    'Relative Doppler Frequency');

plot( ...
    validTime, ...
    rawCarrierVariation, ...
    'o', ...
    'MarkerSize', 4);

hold on;

plot( ...
    validTime, ...
    interpolatedCarrierVariation, ...
    '.-', ...
    'MarkerSize', 8, ...
    'LineWidth', 1.0);

yline( ...
    0, ...
    '--', ...
    'Common reference');

grid on;

xlabel('Time (s)');
ylabel('Relative Doppler frequency (Hz)');

title({ ...
    'Raw and Interpolated Relative Doppler Estimate', ...
    sprintf( ...
    ['Common reference carrier = %.3f Hz, ' ...
    'requested resolution = %.6f Hz'], ...
    referenceCarrierFrequency, ...
    requestedDopplerResolutionHz)});

legend( ...
    'Raw FFT-bin Doppler', ...
    'Sub-bin interpolated Doppler', ...
    'Location', ...
    'best');

%% Plot interpolation correction

interpolationCorrection = ...
    validInterpolatedCarrier - ...
    validRawCarrier;

figure( ...
    'Name', ...
    'Interpolation Correction');

plot( ...
    validTime, ...
    interpolationCorrection, ...
    '.-', ...
    'MarkerSize', 8, ...
    'LineWidth', 1.0);

hold on;

yline(0, '--');

yline( ...
    carrierGridSpacing / 2, ...
    ':', ...
    '+0.5 carrier bin');

yline( ...
    -carrierGridSpacing / 2, ...
    ':', ...
    '-0.5 carrier bin');

grid on;

xlabel('Time (s)');
ylabel('Interpolation correction (Hz)');

title({ ...
    'Difference between Interpolated and Raw Estimates', ...
    sprintf( ...
    'One carrier-grid bin = %.3f Hz', ...
    carrierGridSpacing)});

%% Plot estimation confidence

figure( ...
    'Name', ...
    'Carrier Estimation Confidence');

plot( ...
    timeVector, ...
    peakToFloorDb, ...
    'LineWidth', 1.1);

hold on;

yline( ...
    minimumPeakToFloorDb, ...
    '--', ...
    'Validity threshold');

grid on;

xlabel('Time (s)');
ylabel('Peak-to-background ratio (dB)');
title('Carrier Estimation Confidence versus Time');

%% Print numerical summary

carrierDifference = ...
    validInterpolatedCarrier - ...
    validRawCarrier;

fprintf('\nCarrier-estimation summary\n');
fprintf('--------------------------------------------------\n');

fprintf('Valid estimates               : %d of %d frames\n', ...
    sum(validEstimateMask), ...
    length(validEstimateMask));

fprintf('Original sample rate          : %.6f Hz\n', ...
    Fs);

fprintf('Resampled sample rate         : %.6f Hz\n', ...
    resampledFs);

fprintf('Selected bandwidth            : %.6f Hz\n', ...
    selectedBandwidth);

fprintf('Resample bandwidth factor     : %.3f\n', ...
    resampleBandwidthFactor);

fprintf('Explicit FIR cutoff           : %.6f Hz\n', ...
    filterCutoffFrequency);

fprintf('Observation time              : %.9f s\n', ...
    observationTime);

fprintf('Requested Doppler resolution  : %.9f Hz\n', ...
    requestedDopplerResolutionHz);

fprintf('Achieved Fourier resolution   : %.9f Hz\n', ...
    achievedDopplerResolutionHz);

fprintf('Displayed Doppler-grid step   : %.9f Hz\n', ...
    carrierGridSpacing);

fprintf('Physical Fourier scale        : %.9f Hz\n', ...
    fourierCarrierScale);

fprintf('\nRaw FFT-bin estimate\n');

fprintf('Mean carrier frequency        : %.3f Hz\n', ...
    mean(validRawCarrier));

fprintf('Median carrier frequency      : %.3f Hz\n', ...
    median(validRawCarrier));

fprintf('Standard deviation            : %.3f Hz\n', ...
    std(validRawCarrier));

fprintf('\nSub-bin interpolated estimate\n');

fprintf('Mean carrier frequency        : %.3f Hz\n', ...
    mean(validInterpolatedCarrier));

fprintf('Median carrier frequency      : %.3f Hz\n', ...
    median(validInterpolatedCarrier));

fprintf('Standard deviation            : %.3f Hz\n', ...
    std(validInterpolatedCarrier));

fprintf('\nInterpolation comparison\n');

fprintf('Mean interpolation correction : %.3f Hz\n', ...
    mean(carrierDifference));

fprintf('Correction standard deviation : %.3f Hz\n', ...
    std(carrierDifference));

fprintf('Maximum absolute correction   : %.3f Hz\n', ...
    max(abs(carrierDifference)));

fprintf('Maximum allowed correction    : %.3f Hz\n', ...
    carrierGridSpacing / 2);

%% Local function

function iqSignal = readIQSegment( ...
    fid, ...
    startComplexSample, ...
    numberOfComplexSamples, ...
    bytesPerScalar, ...
    readType)

    if numberOfComplexSamples <= 0

        iqSignal = complex(zeros(0, 1));
        return;
    end

    byteOffset = ...
        startComplexSample * ...
        2 * bytesPerScalar;

    seekStatus = fseek( ...
        fid, ...
        byteOffset, ...
        'bof');

    if seekStatus ~= 0
        error('Could not seek to the requested file position.');
    end

    rawData = fread( ...
        fid, ...
        [2, numberOfComplexSamples], ...
        readType);

    if isempty(rawData)

        iqSignal = complex(zeros(0, 1));
        return;
    end

    iqSignal = ...
        rawData(1, :).'+ ...
        1i * rawData(2, :).';
end
